#!/usr/bin/env python
import os

print('Content-type: text')
print('')

envs = [
    'SERVER_SOFTWARE',
    'SERVER_NAME',
    'GATEWAY_INTERFACE',
    'SERVER_PROTOCOL',
    'SERVER_PORT',
    'REQUEST_METHOD',
    'PATH_INFO',
    'PATH_TRANSLATED',
    'SCRIPT_NAME',
    'QUERY_STRING',
    'REMOTE_ADDR',
    'AUTH_TYPE',
    'REMOTE_USER',
    'CONTENT_TYPE',
    'CONTENT_LENGTH',
    'HTTP_REFERER',
    'HTTP_ACCEPT',
    'HTTP_USER_AGENT',
    'HTTP_COOKIE',
]

for env in envs:
    print('{} - {}'.format(env, os.environ.get(env)))
